name: Release

on:
  workflow_dispatch:

jobs:
  release:

    name: Release to Maven Central
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Maven Central
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          ./mvnw -B release:prepare release:perform -Dpassword=${{ secrets.GITHUB_TOKEN }}
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}